"""Fenced in-process runner for sequential Phase 4 page image generation."""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from io import BytesIO
from typing import cast
from uuid import UUID

from PIL import Image, UnidentifiedImageError
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from katha.core.config import get_settings
from katha.core.database import async_session_factory
from katha.features.characters.models import Character
from katha.features.stories.models import Story, StoryPage
from katha.features.story_images.models import ImagePageSnapshot
from katha.features.story_images.ports import (
    ImageProviderRejectedError,
    ImageProviderUnavailableError,
    ImageReferenceInvalidError,
    StoryImageAI,
    StoryImageStorage,
)

logger = logging.getLogger(__name__)


class ClaimLost(RuntimeError):  # noqa: N818
    """The DB claim has been reclaimed, so this worker must make no more writes."""


class DuplicateSameClaim(RuntimeError):  # noqa: N818
    """A second in-process runner tried to execute an already-owned claim."""


class InvalidGeneratedImage(RuntimeError):  # noqa: N818
    """Generated bytes fail the configured WebP/size/byte validation."""


class ReferenceUnavailable(RuntimeError):  # noqa: N818
    """One selected R2 reference could not be downloaded safely."""


_active_runner_keys: set[tuple[int, UUID]] = set()
_semaphores: dict[int, asyncio.Semaphore] = {}


async def run_image_generation(
    story_id: int,
    claim_id: UUID,
    provider: StoryImageAI,
    storage: StoryImageStorage,
) -> None:
    """Run one immutable page target list; never reuse a request-scoped DB session."""

    runner_key = (story_id, claim_id)
    # This registration is intentionally synchronous before the first await. With the documented
    # one-app-instance MVP assumption, it closes the same-claim duplicate/finalizer window.
    if runner_key in _active_runner_keys:
        logger.info(
            "Ignoring duplicate image runner", extra={"story_id": story_id, "job_id": str(claim_id)}
        )
        return
    _active_runner_keys.add(runner_key)
    semaphore = _semaphore_for_current_settings()
    acquired = False
    candidate_url: str | None = None
    candidate_key: str | None = None
    current_page_id: int | None = None
    primary_started = False
    try:
        acquired = await _acquire_with_heartbeat(semaphore, story_id, claim_id)
        if not acquired:
            return
        target_page_ids = await _snapshot_target_pages(story_id, claim_id)
        primary_started = True
        for page_id in target_page_ids:
            current_page_id = page_id
            candidate_url = None
            candidate_key = None
            try:
                snapshot = await _claim_page(story_id, page_id, claim_id, storage)
                page_deadline = (
                    asyncio.get_running_loop().time()
                    + get_settings().IMAGE_PAGE_OPERATION_TIMEOUT_SECONDS
                )
                image_bytes = await _generate_page_image(snapshot, provider, storage)
                candidate_key = _image_object_key(
                    story_id,
                    snapshot.page_id,
                    claim_id,
                    snapshot.attempt_count,
                )
                if not await _heartbeat(story_id, claim_id):
                    raise ClaimLost()
                remaining_operation_seconds = page_deadline - asyncio.get_running_loop().time()
                if remaining_operation_seconds <= 0:
                    raise ImageProviderUnavailableError("Image operation timed out")
                candidate_url = await _upload_once_with_retry(
                    storage,
                    candidate_key,
                    image_bytes,
                    timeout_seconds=remaining_operation_seconds,
                )
                completed = await _complete_page(
                    story_id,
                    snapshot.page_id,
                    claim_id,
                    candidate_url,
                )
                if not completed:
                    raise ClaimLost()
            except PageAlreadyCompleted:
                current_page_id = None
                continue
            except ImageProviderRejectedError:
                if not await _mark_page_failed(story_id, page_id, claim_id, "PROVIDER_REJECTED"):
                    raise ClaimLost()
                current_page_id = None
                continue
            except InvalidGeneratedImage:
                if not await _mark_page_failed(story_id, page_id, claim_id, "INVALID_IMAGE"):
                    raise ClaimLost()
                current_page_id = None
                continue
            except ImageProviderUnavailableError:
                await _mark_then_finalize(story_id, claim_id, page_id, "PROVIDER_UNAVAILABLE")
                return
            except ReferenceUnavailable:
                await _mark_then_finalize(story_id, claim_id, page_id, "REFERENCE_UNAVAILABLE")
                return
            except StorageUploadFailed:
                if candidate_key is not None and current_page_id is not None:
                    await _cleanup_orphan_if_safe(
                        storage, story_id, current_page_id, candidate_key, candidate_url
                    )
                await _mark_then_finalize(story_id, claim_id, page_id, "R2_UPLOAD_FAILED")
                return
            current_page_id = None
            candidate_url = None
            candidate_key = None
        await _finalize_claim(story_id, claim_id)
    except DuplicateSameClaim:
        # Same UUID is not enough fencing; this path must never reset/finalize the primary runner.
        logger.info(
            "Stopping duplicate same-claim image runner",
            extra={"story_id": story_id, "job_id": str(claim_id)},
        )
    except ClaimLost:
        if candidate_key is not None and current_page_id is not None:
            await _cleanup_orphan_if_safe(
                storage, story_id, current_page_id, candidate_key, candidate_url
            )
        logger.info(
            "Stopping stale image runner", extra={"story_id": story_id, "job_id": str(claim_id)}
        )
    except UploadOutcomeUncertain:
        # A timed-out synchronous upload can still finish in its worker thread. Do not delete or
        # mutate the page here; the stale-claim path will reconcile without risking a committed URL.
        logger.warning(
            "Stopping image runner after uncertain R2 upload outcome",
            extra={"story_id": story_id, "job_id": str(claim_id)},
        )
    except CompletionNotPersisted:
        if candidate_key is not None and current_page_id is not None:
            await _cleanup_orphan_if_safe(
                storage, story_id, current_page_id, candidate_key, candidate_url
            )
        await _mark_then_finalize(story_id, claim_id, current_page_id, "INTERNAL_ERROR")
    except CompletionOutcomeUncertain:
        # A fresh reread could not prove whether the DB commit landed. Keep the immutable object
        # and let the stale-claim reconciliation path decide; deleting here could erase a committed
        # asset that merely became temporarily unreadable.
        logger.warning(
            "Stopping image runner after uncertain completion commit",
            extra={"story_id": story_id, "job_id": str(claim_id)},
        )
    except Exception:
        logger.exception(
            "Unexpected Phase 4 image runner failure",
            extra={"story_id": story_id, "job_id": str(claim_id)},
        )
        if candidate_key is not None and current_page_id is not None:
            await _cleanup_orphan_if_safe(
                storage, story_id, current_page_id, candidate_key, candidate_url
            )
        if primary_started:
            await _mark_then_finalize(story_id, claim_id, current_page_id, "INTERNAL_ERROR")
    finally:
        if acquired:
            semaphore.release()
        _active_runner_keys.discard(runner_key)


class PageAlreadyCompleted(RuntimeError):  # noqa: N818
    """The canonical state completed this target after the original snapshot."""


class StorageUploadFailed(RuntimeError):  # noqa: N818
    """Upload retry using the same bytes/key exhausted its one retry."""


class UploadOutcomeUncertain(RuntimeError):  # noqa: N818
    """An upload timed out after the background thread may already have written the object."""


class CompletionOutcomeUncertain(RuntimeError):  # noqa: N818
    """The completion commit failed and its durable outcome could not be read safely."""


class CompletionNotPersisted(RuntimeError):  # noqa: N818
    """A canonical reread proved the completion write did not persist."""


def _semaphore_for_current_settings() -> asyncio.Semaphore:
    limit = get_settings().IMAGE_MAX_CONCURRENT_JOBS
    semaphore = _semaphores.get(limit)
    if semaphore is None:
        semaphore = asyncio.Semaphore(limit)
        _semaphores[limit] = semaphore
    return semaphore


async def _acquire_with_heartbeat(
    semaphore: asyncio.Semaphore,
    story_id: int,
    claim_id: UUID,
) -> bool:
    """Wait for global local concurrency while keeping a queued claim fresh."""

    acquire_task = asyncio.create_task(semaphore.acquire())
    interval = max(1.0, min(get_settings().IMAGE_GENERATION_STALE_SECONDS / 3, 30.0))
    try:
        while True:
            done, _ = await asyncio.wait({acquire_task}, timeout=interval)
            if acquire_task in done:
                return True
            if not await _heartbeat(story_id, claim_id):
                acquire_task.cancel()
                await asyncio.gather(acquire_task, return_exceptions=True)
                return False
    except BaseException:
        acquire_task.cancel()
        await asyncio.gather(acquire_task, return_exceptions=True)
        raise


async def _snapshot_target_pages(story_id: int, claim_id: UUID) -> tuple[int, ...]:
    async with async_session_factory() as session:
        story = await _locked_current_story(session, story_id, claim_id)
        pages = await _locked_pages(session, story_id)
        if any(_page_status(page) == "generating" for page in pages):
            await session.rollback()
            raise DuplicateSameClaim()
        target_ids = tuple(
            cast(int, page.id) for page in pages if _page_status(page) in {"pending", "failed"}
        )
        story.image_generation_heartbeat_at = await _database_now(session)  # type: ignore[assignment]
        await session.commit()
        return target_ids


async def _claim_page(
    story_id: int,
    page_id: int,
    claim_id: UUID,
    storage: StoryImageStorage,
) -> ImagePageSnapshot:
    async with async_session_factory() as session:
        story = await _locked_current_story(session, story_id, claim_id)
        page_result = await session.execute(
            select(StoryPage)
            .where(StoryPage.id == page_id, StoryPage.story_id == story_id)
            .with_for_update()
        )
        page = page_result.scalar_one_or_none()
        if page is None:
            await session.rollback()
            raise ClaimLost()
        current_status = _page_status(page)
        if current_status == "completed" and _has_valid_url(page):
            await session.rollback()
            raise PageAlreadyCompleted()
        if current_status == "generating":
            await session.rollback()
            raise DuplicateSameClaim()
        if current_status not in {"pending", "failed"}:
            await session.rollback()
            raise ClaimLost()
        prompt = cast(str | None, page.image_prompt_en)
        attempt_count = cast(int, page.image_attempt_count or 0) + 1
        page.image_status = "generating"  # type: ignore[assignment]
        page.image_error_code = None  # type: ignore[assignment]
        page.image_attempt_count = attempt_count  # type: ignore[assignment]
        now = await _database_now(session)
        story.image_generation_heartbeat_at = now  # type: ignore[assignment]
        story.updated_at = now  # type: ignore[assignment]

        # Persist the ownership transition before surfacing any local page error so the
        # fenced failure handler can reliably move generating -> failed.
        if not prompt or not prompt.strip():
            await session.commit()
            raise InvalidGeneratedImage()

        try:
            characters = await _selected_characters(session, page)
            urls = _reference_urls(
                characters,
                cast(list[int] | None, page.image_character_ids) or [],
                storage,
            )
        except ReferenceUnavailable:
            await session.commit()
            raise

        await session.commit()
        return ImagePageSnapshot(
            story_id=story_id,
            page_id=page_id,
            page_no=cast(int, page.page_no),
            prompt_en=prompt,
            reference_urls=urls,
            attempt_count=attempt_count,
        )


async def _generate_page_image(
    snapshot: ImagePageSnapshot,
    provider: StoryImageAI,
    storage: StoryImageStorage,
) -> bytes:
    settings = get_settings()
    reference_limit = min(settings.IMAGE_MAX_OUTPUT_BYTES, 10 * 1024 * 1024)
    try:
        async with asyncio.timeout(settings.image_provider_retry_budget_seconds):
            try:
                references: tuple[bytes, ...] = tuple(
                    await asyncio.gather(
                        *(
                            asyncio.to_thread(
                                storage.download_public_reference,
                                url,
                                reference_limit,
                            )
                            for url in snapshot.reference_urls
                        )
                    )
                )
            except Exception as exc:
                raise ReferenceUnavailable("Reference image could not be loaded") from exc

            try:
                image_bytes = await provider.generate_image(snapshot.prompt_en, references)
            except ImageReferenceInvalidError as exc:
                raise ReferenceUnavailable("Reference image is invalid") from exc
    except TimeoutError as exc:
        raise ImageProviderUnavailableError("Image operation timed out") from exc
    except (
        ImageProviderUnavailableError,
        ImageProviderRejectedError,
        ReferenceUnavailable,
    ):
        raise
    _validate_generated_image(
        image_bytes, settings.OPENAI_IMAGE_SIZE, settings.IMAGE_MAX_OUTPUT_BYTES
    )
    return image_bytes


async def _upload_once_with_retry(
    storage: StoryImageStorage,
    key: str,
    data: bytes,
    *,
    timeout_seconds: float,
) -> str:
    """Retry the same immutable key within the remaining whole-page deadline."""

    upload_task: asyncio.Task[str] | None = None
    try:
        async with asyncio.timeout(timeout_seconds):
            for attempt in range(2):
                upload_task = asyncio.create_task(
                    asyncio.to_thread(storage.upload_image, key, data)
                )
                try:
                    return await asyncio.shield(upload_task)
                except Exception as exc:
                    if attempt == 1:
                        raise StorageUploadFailed("R2 upload retry exhausted") from exc
    except TimeoutError as exc:
        # Shield keeps the boto3 call alive. Drain it before returning so the runner still owns
        # the semaphore while the bounded SDK operation reaches a known terminal outcome.
        if upload_task is not None:
            try:
                await upload_task
            except Exception:
                pass
        raise UploadOutcomeUncertain("R2 upload timed out") from exc
    raise AssertionError("unreachable")


async def _complete_page(
    story_id: int,
    page_id: int,
    claim_id: UUID,
    image_url: str,
) -> bool:
    async with async_session_factory() as session:
        try:
            story = await _locked_current_story(session, story_id, claim_id)
        except ClaimLost:
            return False
        result = await session.execute(
            select(StoryPage)
            .where(StoryPage.id == page_id, StoryPage.story_id == story_id)
            .with_for_update()
        )
        page = result.scalar_one_or_none()
        if page is None or _page_status(page) != "generating":
            await session.rollback()
            return False
        page.image_url = image_url  # type: ignore[assignment]
        page.image_status = "completed"  # type: ignore[assignment]
        page.image_error_code = None  # type: ignore[assignment]
        page.review_status = "pending"  # type: ignore[assignment]
        page.reviewed_by = None  # type: ignore[assignment]
        page.reviewed_at = None  # type: ignore[assignment]
        page.review_notes = None  # type: ignore[assignment]
        now = await _database_now(session)
        story.image_generation_heartbeat_at = now  # type: ignore[assignment]
        story.updated_at = now  # type: ignore[assignment]
        try:
            await session.commit()
        except Exception as exc:
            await _rollback_quietly(session)
            outcome = await _canonical_page_matches_url(story_id, page_id, image_url)
            if outcome is None:
                raise CompletionOutcomeUncertain() from exc
            if outcome:
                return True
            raise CompletionNotPersisted() from exc
        return True


async def _mark_page_failed(story_id: int, page_id: int, claim_id: UUID, error_code: str) -> bool:
    async with async_session_factory() as session:
        try:
            story = await _locked_current_story(session, story_id, claim_id)
        except ClaimLost:
            return False
        result = await session.execute(
            select(StoryPage)
            .where(StoryPage.id == page_id, StoryPage.story_id == story_id)
            .with_for_update()
        )
        page = result.scalar_one_or_none()
        if page is None or _page_status(page) != "generating":
            await session.rollback()
            return False
        page.image_status = "failed"  # type: ignore[assignment]
        page.image_error_code = error_code  # type: ignore[assignment]
        now = await _database_now(session)
        story.image_generation_heartbeat_at = now  # type: ignore[assignment]
        story.updated_at = now  # type: ignore[assignment]
        try:
            await session.commit()
        except Exception:
            await _rollback_quietly(session)
            return await _canonical_page_matches_failure(
                story_id,
                page_id,
                error_code,
            )
        return True


async def _mark_then_finalize(
    story_id: int,
    claim_id: UUID,
    page_id: int | None,
    error_code: str,
) -> None:
    if page_id is not None:
        marked = await _mark_page_failed(story_id, page_id, claim_id, error_code)
        if not marked:
            return
    await _finalize_claim(story_id, claim_id)


async def _finalize_claim(story_id: int, claim_id: UUID) -> bool:
    """Transition only the current UUID claim; old workers cannot finalize a reclaimed job."""

    async with async_session_factory() as session:
        try:
            story = await _locked_current_story(session, story_id, claim_id)
        except ClaimLost:
            return False
        pages = await _locked_pages(session, story_id)
        all_completed = bool(pages) and all(
            _page_status(page) == "completed" and _has_valid_url(page) for page in pages
        )
        if all_completed:
            story.status = "pending_review"  # type: ignore[assignment]
        else:
            for page in pages:
                if _page_status(page) == "generating":
                    page.image_status = "failed"  # type: ignore[assignment]
                    page.image_error_code = "JOB_INTERRUPTED"  # type: ignore[assignment]
            story.status = "text_confirmed"  # type: ignore[assignment]
        story.image_generation_claim_id = None  # type: ignore[assignment]
        story.image_generation_heartbeat_at = None  # type: ignore[assignment]
        story.updated_at = await _database_now(session)  # type: ignore[assignment]
        await session.commit()
        return True


async def _heartbeat(story_id: int, claim_id: UUID) -> bool:
    async with async_session_factory() as session:
        try:
            story = await _locked_current_story(session, story_id, claim_id)
        except ClaimLost:
            return False
        now = await _database_now(session)
        story.image_generation_heartbeat_at = now  # type: ignore[assignment]
        story.updated_at = now  # type: ignore[assignment]
        await session.commit()
        return True


async def _locked_current_story(session: AsyncSession, story_id: int, claim_id: UUID) -> Story:
    result = await session.execute(select(Story).where(Story.id == story_id).with_for_update())
    story = result.scalar_one_or_none()
    if (
        story is None
        or story.status != "generating_images"
        or story.image_generation_claim_id != claim_id
    ):
        await session.rollback()
        raise ClaimLost()
    return story


async def _locked_pages(session: AsyncSession, story_id: int) -> list[StoryPage]:
    result = await session.execute(
        select(StoryPage)
        .where(StoryPage.story_id == story_id)
        .order_by(StoryPage.page_no)
        .with_for_update()
    )
    return list(result.scalars().all())


async def _selected_characters(session: AsyncSession, page: StoryPage) -> list[Character]:
    selected_ids = cast(list[int] | None, page.image_character_ids) or []
    if not selected_ids:
        return []
    result = await session.execute(
        select(Character).where(Character.id.in_(selected_ids)).order_by(Character.id)
    )
    characters = list(result.scalars().all())
    if {cast(int, character.id) for character in characters} != set(selected_ids):
        raise ReferenceUnavailable("Selected character mapping is no longer valid")
    return characters


def _reference_urls(
    characters: list[Character],
    selected_ids: list[int],
    storage: StoryImageStorage,
) -> tuple[str, ...]:
    by_id = {cast(int, character.id): character for character in characters}
    urls: list[str] = []
    for character_id in sorted(selected_ids):
        character = by_id.get(character_id)
        ref_image_urls = cast(list[str] | None, character.ref_image_urls) if character else None
        url = next(
            (
                item
                for item in ref_image_urls or []
                if isinstance(item, str)
                and item.strip()
                and storage.key_from_public_url(item) is not None
            ),
            None,
        )
        if url is None:
            raise ReferenceUnavailable("Selected character is missing a reference")
        urls.append(url)
    return tuple(urls)


async def _cleanup_orphan_if_safe(
    storage: StoryImageStorage,
    story_id: int,
    page_id: int,
    key: str,
    candidate_url: str | None,
) -> None:
    """Delete only when a canonical reread proves no row points at this immutable asset."""

    referenced = await _canonical_page_references_candidate(
        storage, story_id, page_id, key, candidate_url
    )
    if referenced is None:
        logger.warning(
            "Skipping orphan cleanup because canonical image state could not be verified",
            extra={"story_id": story_id, "page_id": page_id},
        )
        return
    if referenced:
        return
    try:
        await asyncio.to_thread(storage.delete_object, key)
    except Exception:
        logger.warning(
            "Best-effort image orphan cleanup failed",
            extra={"story_id": story_id, "page_id": page_id},
        )


async def _canonical_page_matches_url(
    story_id: int, page_id: int, candidate_url: str
) -> bool | None:
    """Read a fresh session after a completion commit loses its acknowledgement."""

    try:
        async with async_session_factory() as session:
            result = await session.execute(
                select(StoryPage.image_status, StoryPage.image_url).where(
                    StoryPage.id == page_id, StoryPage.story_id == story_id
                )
            )
            row = result.one_or_none()
            canonical_status = cast(str | None, row[0]) if row is not None else None
            canonical_url = cast(str | None, row[1]) if row is not None else None
            await session.rollback()
    except Exception:
        return None
    return canonical_status == "completed" and canonical_url == candidate_url


async def _canonical_page_matches_failure(
    story_id: int,
    page_id: int,
    error_code: str,
) -> bool:
    """Verify a failed-page write after its commit acknowledgement is lost."""

    try:
        async with async_session_factory() as session:
            result = await session.execute(
                select(StoryPage.image_status, StoryPage.image_error_code).where(
                    StoryPage.id == page_id,
                    StoryPage.story_id == story_id,
                )
            )
            row = result.one_or_none()
            canonical_status = cast(str | None, row[0]) if row is not None else None
            canonical_error = cast(str | None, row[1]) if row is not None else None
            await session.rollback()
    except Exception:
        return False
    return canonical_status == "failed" and canonical_error == error_code


async def _canonical_page_references_candidate(
    storage: StoryImageStorage,
    story_id: int,
    page_id: int,
    key: str,
    candidate_url: str | None,
) -> bool | None:
    """Check both URL and safe R2 key when an upload acknowledgement may have been lost."""

    try:
        async with async_session_factory() as session:
            result = await session.execute(
                select(StoryPage.image_url).where(
                    StoryPage.id == page_id, StoryPage.story_id == story_id
                )
            )
            canonical_url = cast(str | None, result.scalar_one_or_none())
            await session.rollback()
    except Exception:
        return None

    if candidate_url is not None and canonical_url == candidate_url:
        return True
    if not isinstance(canonical_url, str) or not canonical_url.strip():
        return False
    try:
        canonical_key = await asyncio.to_thread(storage.key_from_public_url, canonical_url)
    except Exception:
        return None
    return canonical_key == key


async def _rollback_quietly(session: AsyncSession) -> None:
    """A lost connection can make rollback fail; the canonical reread remains authority."""

    try:
        await session.rollback()
    except Exception:
        pass


def _image_object_key(story_id: int, page_id: int, claim_id: UUID, attempt_count: int) -> str:
    return f"stories/{story_id}/pages/{page_id}/{claim_id}-{attempt_count}.webp"


def _validate_generated_image(data: bytes, size: str, max_bytes: int) -> None:
    if not data or len(data) > max_bytes:
        raise InvalidGeneratedImage("Image bytes exceed the configured cap")
    try:
        width_text, height_text = size.split("x", 1)
        expected_size = (int(width_text), int(height_text))
        with Image.open(BytesIO(data)) as image:
            if image.format != "WEBP":
                raise InvalidGeneratedImage("Generated output is not WebP")
            image.load()
            if image.size != expected_size:
                raise InvalidGeneratedImage("Generated output dimensions are incorrect")
    except (UnidentifiedImageError, OSError, ValueError) as exc:
        if isinstance(exc, InvalidGeneratedImage):
            raise
        raise InvalidGeneratedImage("Generated output is invalid") from exc


def _page_status(page: StoryPage) -> str:
    value = cast(str | None, page.image_status) or "pending"
    return value if value in {"pending", "generating", "completed", "failed"} else "pending"


def _has_valid_url(page: StoryPage) -> bool:
    return isinstance(page.image_url, str) and bool(page.image_url.strip())


async def _database_now(session: AsyncSession) -> datetime:
    result = await session.execute(select(func.clock_timestamp()))
    value = cast(datetime, result.scalar_one())
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)
