import type { ContentLanguage } from '@/features/language/ContentLanguageProvider';

const vi = {
  practiceTitle: 'Luyện nói câu Khmer thông dụng',
  practiceSubtitle: 'Nghe câu mẫu, ghi âm giọng của bạn rồi gửi để chấm.',
  loading: 'Đang tải bài luyện nói…',
  preparingSession: 'Đang chuẩn bị phiên luyện nói…',
  loadFailed: 'Không thể tải bài luyện nói.',
  sessionFailed: 'Không thể chuẩn bị phiên luyện nói.',
  noSentences: 'Chưa có câu luyện nói nào.',
  retryLoad: 'Tải lại',
  skipSentence: 'Bỏ qua câu này',
  skippedSentence: 'Đã bỏ qua',
  sentenceProgress: 'Câu {current}/{total}',
  level: 'Cấp độ {level}',
  meaning: 'Nghĩa tiếng Việt',
  transliteration: 'Phiên âm',
  listenSample: 'Nghe câu mẫu',
  loadingSample: 'Đang tải câu mẫu…',
  stopSample: 'Dừng câu mẫu',
  sampleFailed: 'Không thể phát câu mẫu. Vui lòng thử lại.',
  microphoneUnsupported: 'Trình duyệt này chưa hỗ trợ ghi âm. Hãy dùng Chrome, Edge hoặc Safari mới.',
  microphoneInsecure: 'Micro chỉ hoạt động qua HTTPS. Hãy mở Katha bằng kết nối bảo mật rồi thử lại.',
  microphoneDenied: 'Bạn chưa cho phép dùng micro. Hãy bật quyền micro trong trình duyệt rồi thử lại.',
  microphoneUnavailable: 'Không tìm thấy micro hoặc micro đang được ứng dụng khác sử dụng.',
  microphoneFailed: 'Không thể bắt đầu ghi âm. Vui lòng kiểm tra micro rồi thử lại.',
  readyHint: 'Nghe mẫu trước, sau đó nói rõ cả câu trong tối đa {seconds} giây.',
  privacyNotice: 'Bản ghi chỉ được gửi để nhận dạng và chấm điểm; Katha không lưu âm thanh gốc.',
  requestingPermission: 'Đang xin quyền sử dụng micro…',
  startRecording: 'Bắt đầu ghi âm',
  stopRecording: 'Dừng ghi âm',
  recording: 'Đang ghi âm',
  seconds: '{seconds} giây',
  recordingReady: 'Đã ghi âm xong. Hãy nghe lại hoặc gửi để chấm.',
  processingRecording: 'Đang kiểm tra tín hiệu và chuẩn hóa bản ghi…',
  playRecording: 'Nghe bản ghi',
  stopRecordingPlayback: 'Dừng nghe bản ghi',
  retryRecording: 'Ghi âm lại',
  submit: 'Gửi và chấm điểm',
  submitting: 'Đang nhận diện và chấm…',
  submitFailed: 'Không thể chấm bản ghi. Bản ghi vẫn được giữ để bạn thử gửi lại.',
  emptyRecording: 'Không thu được âm thanh. Hãy nói gần micro hơn rồi thử lại.',
  silentRecording: 'Không phát hiện giọng nói đủ rõ. Hãy nói gần micro hơn rồi ghi lại.',
  recordingProcessingFailed: 'Không thể xử lý bản ghi trên trình duyệt này. Hãy dùng Chrome, Edge hoặc Safari mới.',
  score: '{score} điểm',
  heardAs: 'Hệ thống nghe được',
  confidence: 'Độ tin cậy',
  characterAccuracy: 'Độ chính xác câu',
  termCoverage: 'Từ cần nói',
  feedback: 'Nhận xét',
  matched: 'Đã nói đúng',
  missing: 'Cần luyện thêm',
  nextSentence: 'Câu tiếp theo',
  viewResults: 'Xem kết quả',
  continueSpeaking: 'Tiếp tục luyện nói',
  backToStory: 'Quay lại truyện',
  resultsTitle: 'Kết quả hành trình học',
  resultsSubtitle: 'Bạn đã hoàn thành bài học văn hóa Khmer.',
  overallScore: 'Điểm phát âm',
  journeySummary: 'Tổng kết các phần đã học',
  learningDetails: 'Chi tiết hành trình học',
  completedSections: 'phần đã hoàn thành',
  recognitionStage: 'Nhận diện hình ảnh',
  keywordStage: 'Làm quen từ khóa',
  vocabularySectionHelp: 'Các từ Khmer bạn đã làm quen trong bài học.',
  readingStage: 'Nghe và đọc truyện',
  readingSectionHelp: 'Tiến trình đọc nội dung và nghe giọng kể Khmer.',
  readingCompleted: 'Đọc truyện',
  listeningCompleted: 'Nghe truyện',
  pagesRead: 'Đã đọc {done}/{total} trang',
  pagesListened: 'Đã nghe {done}/{total} trang',
  speakingStage: 'Luyện nói',
  speakingSectionHelp: 'Điểm phát âm và kết quả của từng câu đã luyện.',
  completedStage: 'Hoàn thành',
  keywordCount: '{count} từ khóa',
  storyPageCount: '{count} trang truyện',
  speakingAttemptCount: '{done}/{total} câu đã luyện',
  skippedCount: 'Bỏ qua {count} câu',
  speakingDetails: 'Chi tiết luyện nói',
  noSpeakingAttempts: 'Bạn đã bỏ qua các câu luyện nói nên chưa có điểm phát âm.',
  excellent: 'Rất tốt! Bạn nói rõ và đủ câu.',
  good: 'Khá tốt! Hãy luyện thêm những phần còn thiếu.',
  keepPracticing: 'Tiếp tục luyện để câu nói rõ hơn nhé.',
  sentenceResult: 'Kết quả câu {number}',
  nextJourney: 'Bạn muốn khám phá gì tiếp theo?',
  newRecognition: 'Nhận diện mới',
  newRecognitionHelp: 'Chụp hoặc tải một hình ảnh văn hóa Khmer khác.',
  exploreMuseum: 'Khám phá bảo tàng 360',
  exploreMuseumHelp: 'Tham quan không gian và hiện vật văn hóa Khmer tương tác.',
  practiceAgain: 'Luyện lại từ đầu',
  practiceAgainHelp: 'Giữ nguyên ảnh và truyện, quay lại bước nhận diện để học lại.',
  readStoryAgain: 'Đọc lại truyện',
  readStoryAgainHelp: 'Quay lại câu chuyện và nghe phần đọc một lần nữa.',
  perfectMatch: 'Đủ các phần cần nói',
} as const;

const km: Record<keyof typeof vi, string> = {
  practiceTitle: 'ហាត់និយាយប្រយោគខ្មែរប្រើប្រាស់ប្រចាំថ្ងៃ',
  practiceSubtitle: 'ស្តាប់ប្រយោគគំរូ ថតសំឡេងរបស់អ្នក រួចផ្ញើដើម្បីដាក់ពិន្ទុ។',
  loading: 'កំពុងផ្ទុកមេរៀនហាត់និយាយ…',
  preparingSession: 'កំពុងរៀបចំវគ្គហាត់និយាយ…',
  loadFailed: 'មិនអាចផ្ទុកមេរៀនហាត់និយាយបានទេ។',
  sessionFailed: 'មិនអាចរៀបចំវគ្គហាត់និយាយបានទេ។',
  noSentences: 'មិនទាន់មានប្រយោគសម្រាប់ហាត់និយាយទេ។',
  retryLoad: 'ផ្ទុកឡើងវិញ',
  skipSentence: 'រំលងប្រយោគនេះ',
  skippedSentence: 'បានរំលង',
  sentenceProgress: 'ប្រយោគ {current}/{total}',
  level: 'កម្រិត {level}',
  meaning: 'អត្ថន័យជាភាសាវៀតណាម',
  transliteration: 'សូរសព្ទ',
  listenSample: 'ស្តាប់ប្រយោគគំរូ',
  loadingSample: 'កំពុងផ្ទុកប្រយោគគំរូ…',
  stopSample: 'បញ្ឈប់សំឡេងគំរូ',
  sampleFailed: 'មិនអាចចាក់ប្រយោគគំរូបានទេ។ សូមព្យាយាមម្តងទៀត។',
  microphoneUnsupported: 'កម្មវិធីរុករកនេះមិនទាន់គាំទ្រការថតសំឡេងទេ។ សូមប្រើ Chrome, Edge ឬ Safari ជំនាន់ថ្មី។',
  microphoneInsecure: 'មីក្រូហ្វូនដំណើរការតែតាម HTTPS ប៉ុណ្ណោះ។ សូមបើក Katha តាមការតភ្ជាប់សុវត្ថិភាព។',
  microphoneDenied: 'អ្នកមិនទាន់អនុញ្ញាតឱ្យប្រើមីក្រូហ្វូនទេ។ សូមបើកសិទ្ធិមីក្រូហ្វូន ហើយព្យាយាមម្តងទៀត។',
  microphoneUnavailable: 'រកមិនឃើញមីក្រូហ្វូន ឬមីក្រូហ្វូនកំពុងត្រូវបានប្រើ។',
  microphoneFailed: 'មិនអាចចាប់ផ្តើមថតសំឡេងបានទេ។ សូមពិនិត្យមីក្រូហ្វូន។',
  readyHint: 'ស្តាប់គំរូជាមុន រួចនិយាយប្រយោគឱ្យច្បាស់ក្នុងរយៈពេលមិនលើស {seconds} វិនាទី។',
  privacyNotice: 'សំឡេងថតត្រូវបានផ្ញើសម្រាប់ការសម្គាល់ និងដាក់ពិន្ទុតែប៉ុណ្ណោះ; Katha មិនរក្សាទុកសំឡេងដើមទេ។',
  requestingPermission: 'កំពុងស្នើសុំសិទ្ធិប្រើមីក្រូហ្វូន…',
  startRecording: 'ចាប់ផ្តើមថតសំឡេង',
  stopRecording: 'បញ្ឈប់ការថត',
  recording: 'កំពុងថតសំឡេង',
  seconds: '{seconds} វិនាទី',
  recordingReady: 'បានថតសំឡេងរួច។ សូមស្តាប់ឡើងវិញ ឬផ្ញើដើម្បីដាក់ពិន្ទុ។',
  processingRecording: 'កំពុងពិនិត្យសញ្ញាសំឡេង និងរៀបចំឯកសារថត…',
  playRecording: 'ស្តាប់សំឡេងថត',
  stopRecordingPlayback: 'បញ្ឈប់សំឡេងថត',
  retryRecording: 'ថតម្តងទៀត',
  submit: 'ផ្ញើ និងដាក់ពិន្ទុ',
  submitting: 'កំពុងសម្គាល់សំឡេង និងដាក់ពិន្ទុ…',
  submitFailed: 'មិនអាចដាក់ពិន្ទុបានទេ។ សំឡេងថតនៅតែរក្សាទុកសម្រាប់ផ្ញើម្តងទៀត។',
  emptyRecording: 'មិនមានសំឡេងនៅក្នុងការថតទេ។ សូមនិយាយជិតមីក្រូហ្វូន ហើយព្យាយាមម្តងទៀត។',
  silentRecording: 'មិនបានរកឃើញសំឡេងនិយាយច្បាស់គ្រប់គ្រាន់ទេ។ សូមនិយាយជិតមីក្រូហ្វូន ហើយថតម្តងទៀត។',
  recordingProcessingFailed: 'មិនអាចដំណើរការសំឡេងថតនៅលើកម្មវិធីរុករកនេះបានទេ។ សូមប្រើ Chrome, Edge ឬ Safari ជំនាន់ថ្មី។',
  score: '{score} ពិន្ទុ',
  heardAs: 'ប្រព័ន្ធបានឮ',
  confidence: 'ភាពជឿជាក់',
  characterAccuracy: 'ភាពត្រឹមត្រូវនៃប្រយោគ',
  termCoverage: 'ពាក្យដែលត្រូវនិយាយ',
  feedback: 'មតិយោបល់',
  matched: 'បាននិយាយត្រឹមត្រូវ',
  missing: 'ត្រូវហាត់បន្ថែម',
  nextSentence: 'ប្រយោគបន្ទាប់',
  viewResults: 'មើលលទ្ធផល',
  continueSpeaking: 'បន្តហាត់និយាយ',
  backToStory: 'ត្រឡប់ទៅរឿង',
  resultsTitle: 'លទ្ធផលដំណើរការសិក្សា',
  resultsSubtitle: 'អ្នកបានបញ្ចប់មេរៀនវប្បធម៌ខ្មែរ។',
  overallScore: 'ពិន្ទុបញ្ចេញសំឡេង',
  journeySummary: 'សេចក្តីសង្ខេបផ្នែកដែលបានសិក្សា',
  learningDetails: 'ព័ត៌មានលម្អិតនៃដំណើរសិក្សា',
  completedSections: 'ផ្នែកបានបញ្ចប់',
  recognitionStage: 'សម្គាល់រូបភាព',
  keywordStage: 'ស្គាល់ពាក្យគន្លឹះ',
  vocabularySectionHelp: 'ពាក្យខ្មែរដែលអ្នកបានស្គាល់ក្នុងមេរៀននេះ។',
  readingStage: 'ស្តាប់ និងអានរឿង',
  readingSectionHelp: 'វឌ្ឍនភាពអានខ្លឹមសារ និងស្តាប់សំឡេងនិទានខ្មែរ។',
  readingCompleted: 'អានរឿង',
  listeningCompleted: 'ស្តាប់រឿង',
  pagesRead: 'បានអាន {done}/{total} ទំព័រ',
  pagesListened: 'បានស្តាប់ {done}/{total} ទំព័រ',
  speakingStage: 'ហាត់និយាយ',
  speakingSectionHelp: 'ពិន្ទុបញ្ចេញសំឡេង និងលទ្ធផលប្រយោគនីមួយៗ។',
  completedStage: 'បានបញ្ចប់',
  keywordCount: 'ពាក្យគន្លឹះ {count}',
  storyPageCount: 'រឿង {count} ទំព័រ',
  speakingAttemptCount: 'បានហាត់ {done}/{total} ប្រយោគ',
  skippedCount: 'បានរំលង {count} ប្រយោគ',
  speakingDetails: 'ព័ត៌មានលម្អិតអំពីការហាត់និយាយ',
  noSpeakingAttempts: 'អ្នកបានរំលងប្រយោគហាត់និយាយ ដូច្នេះមិនទាន់មានពិន្ទុបញ្ចេញសំឡេងទេ។',
  excellent: 'ល្អណាស់! អ្នកនិយាយបានច្បាស់ និងគ្រប់ប្រយោគ។',
  good: 'ល្អគួរសម! សូមហាត់បន្ថែមផ្នែកដែលនៅខ្វះ។',
  keepPracticing: 'សូមបន្តហាត់ដើម្បីឱ្យការនិយាយកាន់តែច្បាស់។',
  sentenceResult: 'លទ្ធផលប្រយោគទី {number}',
  nextJourney: 'តើអ្នកចង់ស្វែងយល់អ្វីបន្ទាប់?',
  newRecognition: 'សម្គាល់រូបភាពថ្មី',
  newRecognitionHelp: 'ថត ឬបង្ហោះរូបភាពវប្បធម៌ខ្មែរផ្សេងទៀត។',
  exploreMuseum: 'ស្វែងយល់សារមន្ទីរ 360',
  exploreMuseumHelp: 'ទស្សនាលំហ និងវត្ថុវប្បធម៌ខ្មែរតាមរបៀបអន្តរកម្ម។',
  practiceAgain: 'ហាត់ឡើងវិញពីដំបូង',
  practiceAgainHelp: 'រក្សារូបភាព និងរឿងដដែល ហើយត្រឡប់ទៅជំហានសម្គាល់រូបភាពដើម្បីរៀនឡើងវិញ។',
  readStoryAgain: 'អានរឿងម្តងទៀត',
  readStoryAgainHelp: 'ត្រឡប់ទៅរឿង និងស្តាប់ការអានម្តងទៀត។',
  perfectMatch: 'បាននិយាយគ្រប់ផ្នែក',
};

export function getSpeakingCopy(language: ContentLanguage) {
  return language === 'km' ? km : vi;
}

export function formatSpeakingCopy(
  template: string,
  values: Record<string, string | number>,
) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}
